---
name: Build Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  issues: write

defaults:
  run:
    # Error handling and pipefile must be explicitly set via the default shell
    #   https://github.com/actions/runner/issues/353#issuecomment-1067227665
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch the tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        id: releaser
        uses: goreleaser/goreleaser-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean

  update-documentation:
    name: Update the Documentation
    runs-on: ubuntu-latest
    needs:
      - goreleaser
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch the tags
        run: git fetch --force --tags

      - name: Update the documentation tag reference
        run: |-
          sed -i 's|\(uses: n3tuk/pull-requester\)@\([v[0-9\.]\+\)$|\1@${{ github.ref_name }}|' README.md

      - name: Commit the documentation tag update
        run: |-
          if git diff --exit-code --quiet README.md
            echo "No changes to README.md need to be committed due to a release."
            exit 0
          fi
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit --no-verify \
             -m "Update the GitHub Action tag to ${{ github.ref_name }} in README" \
             -m "Update the version tag for the GitHub Action in the README to ${{ steps.drafter.outputs.id }}\nto account for the latest release."
          git push

  update-tags:
    name: Update Major/Minor Tags
    runs-on: ubuntu-latest
    needs:
      - goreleaser
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch the tags
        run: git fetch --force --tags

      - name: Force update the major tag
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG#v}
          MAJOR=${VERSION%%.*}
          git tag v${MAJOR} ${TAG} -f
          git push origin refs/tags/v${MAJOR} -f

      - name: Force update the major/minor tag
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG#v}
          MAJOR_MINOR=${VERSION%.*}
          git tag v${MAJOR_MINOR} ${TAG} -f
          git push origin refs/tags/v${MAJOR_MINOR} -f
